### ISSUE TITLE
可不可以在Tabbar.Item下加一个select是否选中的布尔值

### ISSUE THREAD

**Issue by liuyongjian** [sincethere/react-native-tabbar#2]

**Comment by chenruimin** [comment]
@liuyongjian 目前在外层Tabbar，有一个回调方法onItemSelected，当选中其中一个item的时候，会回调这个方法并且带index参数。README文档已经更新了，可以看看，usage例子里面也已经使用了这个回调

**Comment by liuyongjian** [comment]
@chenruimin 谢啦
