### ISSUE TITLE
i want a whole circle,not a cutted one...only detected on android phones.

### ISSUE THREAD

**Issue by larryclean** [sincethere/react-native-tabbar#8]
i want a whole circle,not a cutted one...only detected on android phones.
![0e2ca8dc-0701-45da-8738-374a6928686c](https://cloud.githubusercontent.com/assets/18585750/16294666/779945d4-3954-11e6-9fb3-208b9dd4fb20.png)

**Comment by unix** [comment]
look this(react-native bug)
https://rnplay.org/apps/BlGjdQ
https://github.com/facebook/react-native/issues/3198

**Comment by joypatel04** [comment]
@brentvatne Can you please help me with this? On iOS it's render on top of TabBar but in Android it render under the TabBar Same as the above picture!!
